WITH T AS (
    SELECT LENGTH(BIN(CODE)) AS VALUE
    FROM SKILLCODES
    WHERE NAME = 'C#' OR NAME = 'Python'
)
SELECT
    ID,
    EMAIL,
    FIRST_NAME,
    LAST_NAME
FROM DEVELOPERS AS D
WHERE EXISTS (
    SELECT *
    FROM T
    WHERE SUBSTR(BIN(D.SKILL_CODE), -1 * T.VALUE, 1) = '1'
)
ORDER BY ID ASC;